In [13]:
import pandas as pd
df = pd.read_json('exam2_tweets.json')
df.head(5)

,id,link,content,date,retweets,favorites,mentions,hashtags
0,1698308935,https://twitter.com/realDonaldTrump/status/169...,Be sure to tune in and watch Donald Trump on L...,2009-05-04 13:54:25,510,917,NaN,NaN
1,1701461182,https://twitter.com/realDonaldTrump/status/170...,Donald Trump will be appearing on The View tom...,2009-05-04 20:00:10,34,267,NaN,NaN
2,1737479987,https://twitter.com/realDonaldTrump/status/173...,Donald Trump reads Top Ten Financial Tips on L...,2009-05-08 08:38:08,13,19,NaN,NaN
3,1741160716,https://twitter.com/realDonaldTrump/status/174...,New Blog Post: Celebrity Apprentice Finale and...,2009-05-08 15:40:15,11,26,NaN,NaN
4,1773561338,https://twitter.com/realDonaldTrump/status/177...,"""My persona will never be that of a wallflower...",2009-05-12 09:07:28,1375,1945,NaN,NaN

In [14]:
#Which tweet has the most retweets?
content = df.loc[df['retweets'].idxmax(),'content']
content

'# FraudNewsCNN # FNNpic.twitter.com/WYUnHjjUjg'

In [ ]:
#How many tweets have mentions? #20386
print(df['mentions'].count())

#How many tweets have hashtags? #5583
print(df['hashtags'].count())

20386
5583

In [16]:
#How many tweets have hashtags?
print(df['hashtags'].count())

5583

In [17]:
#import json and store file in dictionary
import json
with open('exam2_tweets.json', 'r') as json_file:
    json_list = json.load(json_file)
json_list

[{'id': 1698308935,
  'link': 'https://twitter.com/realDonaldTrump/status/1698308935',
  'content': 'Be sure to tune in and watch Donald Trump on Late Night with David Letterman as he presents the Top Ten List tonight!',
  'date': '2009-05-04 13:54:25',
  'retweets': 510,
  'favorites': 917,
  'mentions': nan,
  'hashtags': nan},
 {'id': 1701461182,
  'link': 'https://twitter.com/realDonaldTrump/status/1701461182',
  'content': 'Donald Trump will be appearing on The View tomorrow morning to discuss Celebrity Apprentice and his new book Think Like A Champion!',
  'date': '2009-05-04 20:00:10',
  'retweets': 34,
  'favorites': 267,
  'mentions': nan,
  'hashtags': nan},
 {'id': 1737479987,
  'link': 'https://twitter.com/realDonaldTrump/status/1737479987',
  'content': 'Donald Trump reads Top Ten Financial Tips on Late Show with David Letterman: http://tinyurl.com/ooafwn - Very funny!',
  'date': '2009-05-08 08:38:08',
  'retweets': 13,
  'favorites': 19,
  'mentions': nan,
  'hashtags': nan},
 {'id': 1741160716,
  'link': 'https://twitter.com/realDonaldTrump/status/1741160716',
  'content': 'New Blog Post: Celebrity Apprentice Finale and Lessons Learned Along the Way: http://tinyurl.com/qlux5e',
  'date': '2009-05-08 15:40:15',
  'retweets': 11,
  'favorites': 26,
  'mentions': nan,
  'hashtags': nan},
 {'id': 1773561338,
  'link': 'https://twitter.com/realDonaldTrump/status/1773561338',
  'content': '"My persona will never be that of a wallflower - I’d rather build walls than cling to them" --Donald J. Trump',
  'date': '2009-05-12 09:07:28',
  'retweets': 1375,
  'favorites': 1945,
  'mentions': nan,
  'hashtags': nan},
 {'id': 1776419923,
  'link': 'https://twitter.com/realDonaldTrump/status/1776419923',
  'content': 'Miss USA Tara Conner will not be fired - "I\'ve always been a believer in second chances." says Donald Trump',
  'date': '2009-05-12 14:21:55',
  'retweets': 29,
  'favorites': 28,
  'mentions': nan,
  'hashtags': nan},
 {'id': 1786560616,
  'link': 'https://twitter.com/realDonaldTrump/status/1786560616',
  'content': 'Listen to an interview with Donald Trump discussing his new book, Think Like A Champion: http://tinyurl.com/qs24vl',
  'date': '2009-05-13 12:38:28',
  'retweets': 15,
  'favorites': 16,
  'mentions': nan,
  'hashtags': nan},
 {'id': 1796477499,
  'link': 'https://twitter.com/realDonaldTrump/status/1796477499',
  'content': '"Strive for wholeness and keep your sense of wonder intact." --Donald J. Trump http://tinyurl.com/pqpfvm',
  'date': '2009-05-14 11:30:40',
  'retweets': 18,
  'favorites': 27,
  'mentions': nan,
  'hashtags': nan},
 {'id': 1806258917,
  'link': 'https://twitter.com/realDonaldTrump/status/1806258917',
  'content': 'Enter the "Think Like A Champion" signed book and keychain contest: http://www.trumpthinklikeachampion.com/contest/',
  'date': '2009-05-15 09:13:13',
  'retweets': 15,
  'favorites': 9,
  'mentions': nan,
  'hashtags': nan},
 {'id': 1820624395,
  'link': 'https://twitter.com/realDonaldTrump/status/1820624395',
  'content': '"When the achiever achieves, it\'s not a plateau, it’s a beginning." --Donald J. Trump http://tinyurl.com/pqpfvm',
  'date': '2009-05-16 17:22:45',
  'retweets': 19,
  'favorites': 47,
  'mentions': nan,
  'hashtags': nan},
 {'id': 1826225450,
  'link': 'https://twitter.com/realDonaldTrump/status/1826225450',
  'content': '"Don’t be afraid of being unique - it\'s like being afraid of your best self." --Donald J. Trump http://tinyurl.com/pqpfvm',
  'date': '2009-05-17 10:00:03',
  'retweets': 40,
  'favorites': 69,
  'mentions': nan,
  'hashtags': nan},
 {'id': 1836131903,
  'link': 'https://twitter.com/realDonaldTrump/status/1836131903',
  'content': '"We win in our lives by having a champion\'s view of each moment." --Donald J. Trump http://tinyurl.com/pqpfvm',
  'date': '2009-05-18 09:26:00',
  'retweets': 74,
  'favorites': 122,
  'mentions': nan,
  'hashtags': nan},
 {'id': 1849558306,
  'link': 'https://twitter.com/realDonaldTrump/status/1849558306',
  'content': '"...these days...we could all use a little of the power of Trumpative thinking." –BarnesandNoble.com http://tinyurl.com/pqpfvm',
  'date': '2009-05-19 12:43:39',
  'retweets': 23,
  'favorites': 23,
  'mentions': nan,
  'hashtags': nan},
 {'id': 1859044981,
  'link': 'https://twitter.com/realDonaldTrump/status/1859044981',
  'content': '"Always know you could be on the precipice of something great." --Donald J. Trump http://tinyurl.com/pqpfvm',
  'date': '2009-05-20 08:25:39',
  'retweets': 28,
  'favorites': 51,
  'mentions': nan,
  'hashtags': nan},
 {'id': 1864367186,
  'link': 'https://twitter.com/realDonaldTrump/status/1864367186',
  'content': 'Read a great interview with Donald Trump that appeared in The New York Times Magazine: http://tinyurl.com/qsx4o6',
  'date': '2009-05-20 17:29:47',
  'retweets': 10,
  'favorites': 11,
  'mentions': nan,
  'hashtags': nan},
 {'id': 1878373267,
  'link': 'https://twitter.com/realDonaldTrump/status/1878373267',
  'content': '"Keep it fast, short and direct - whatever it is." --Donald J. Trump http://tinyurl.com/pqpfvm',
  'date': '2009-05-21 21:59:39',
  'retweets': 61,
  'favorites': 82,
  'mentions': nan,
  'hashtags': nan},
 {'id': 1884022748,
  'link': 'https://twitter.com/realDonaldTrump/status/1884022748',
  'content': 'Don\'t forget to enter the "Think Like A Champion" signed book and keychain contest: http://www.trumpthinklikeachampion.com/contest',
  'date': '2009-05-22 11:28:34',
  'retweets': 13,
  'favorites': 5,
  'mentions': nan,
  'hashtags': nan},
 {'id': 1894284587,
  'link': 'https://twitter.com/realDonaldTrump/status/1894284587',
  'content': 'Did you know Donald Trump is on Facebook? http://www.facebook.com/DonaldTrump - Become a fan today!',
  'date': '2009-05-23 11:11:19',
  'retweets': 58,
  'favorites': 79,
  'mentions': nan,
  'hashtags': nan},
 {'id': 1924074459,
  'link': 'https://twitter.com/realDonaldTrump/status/1924074459',
  'content': '"Your higher self is in direct opposition to your comfort zone." --Donald J. Trump http://tinyurl.com/pqpfvm',
  'date': '2009-05-26 09:42:01',
  'retweets': 50,
  'favorites': 81,
  'mentions': nan,
  'hashtags': nan},
 {'id': 1936022874,
  'link': 'https://twitter.com/realDonaldTrump/status/1936022874',
  'content': 'Read an excerpt from Think Like A Champion by Donald J. Trump: http://bit.ly/11FHpR',
  'date': '2009-05-27 09:18:52',
  'retweets': 6,
  'favorites': 12,
  'mentions': nan,
  'hashtags': nan},
 {'id': 1949899014,
  'link': 'https://twitter.com/realDonaldTrump/status/1949899014',
  'content': '"You have to know when to call it quits and when to keep moving forward." --Donald J. Trump http://www.trumpthinklikeachampion.com',
  'date': '2009-05-28 13:03:34',
  'retweets': 63,
  'favorites': 59,
  'mentions': nan,
  'hashtags': nan},
 {'id': 2019316195,
  'link': 'https://twitter.com/realDonaldTrump/status/2019316195',
  'content': "Check out Donald Trump's new iGoogle Showcase page: http://bit.ly/DdD2A",
  'date': '2009-06-03 13:19:49',
  'retweets': 15,
  'favorites': 20,
  'mentions': nan,
  'hashtags': nan},
 {'id': 2045871770,
  'link': 'https://twitter.com/realDonaldTrump/status/2045871770',
  'content': "“If you don't have problems, you're pretending or you don't run your own business.” –Donald J. Trump http://tinyurl.com/pqpfvm",
  'date': '2009-06-05 13:21:37',
  'retweets': 13,
  'favorites': 31,
  'mentions': nan,
  'hashtags': nan},
 {'id': 2080633709,
  'link': 'https://twitter.com/realDonaldTrump/status/2080633709',
  'content': 'Last week to enter the "Think Like A Champion" signed book and keychain contest: http://www.trumpthinklikeachampion.com/contest/',
  'date': '2009-06-08 15:15:29',
  'retweets': 10,
  'favorites': 3,
  'mentions': nan,
  'hashtags': nan},
 {'id': 2165353946,
  'link': 'https://twitter.com/realDonaldTrump/status/2165353946',
  'content': "Today is Donald Trump's Birthday! Send him your B'day wishes here: http://www.facebook.com/DonaldTrump",
  'date': '2009-06-14 09:25:36',
  'retweets': 26,
  'favorites': 32,
  'mentions': nan,
  'hashtags': nan},
 {'id': 2184650461,
  'link': 'https://twitter.com/realDonaldTrump/status/2184650461',
  'content': 'Thanks to all for your thoughtful birthday wishes – Donald Trump',
  'date': '2009-06-15 18:13:05',
  'retweets': 37,
  'favorites': 38,
  'mentions': nan,
  'hashtags': nan},
 {'id': 2222067805,
  'link': 'https://twitter.com/realDonaldTrump/status/2222067805',
  'content': 'RE: FB Vanity URLs: SF Chronicle - "David Beckham was one of the first, along with Britney Spears & Donald Trump." http://tinyurl.com/ln4lol',
  'date': '2009-06-18 08:26:53',
  'retweets': 19,
  'favorites': 15,
  'mentions': nan,
  'hashtags': nan},
 {'id': 2266041769,
  'link': 'https://twitter.com/realDonaldTrump/status/2266041769',
  'content': "- Wishing a Happy Father's Day to all the Dad's out there - YOU are a champion today and everyday! http://tinyurl.com/kn95ju",
  'date': '2009-06-21 09:47:41',
  'retweets': 61,
  'favorites': 123,
  'mentions': nan,
  'hashtags': nan},
 {'id': 2294519255,
  'link': 'https://twitter.com/realDonaldTrump/status/2294519255',
  'content': '“Expand your life every day.” –Donald J. Trump http://tinyurl.com/pqpfvm',
  'date': '2009-06-23 08:40:38',
  'retweets': 14,
  'favorites': 12,
  'mentions': nan,
  'hashtags': nan},
 {'id': 2317112756,
  'link': 'https://twitter.com/realDonaldTrump/status/2317112756',
  'content': 'Donald Trump’s commercial-free WWE Raw does big rating: http://tinyurl.com/nxvquo',
  'date': '2009-06-24 17:09:19',
  'retweets': 29,
  'favorites': 16,
  'mentions': nan,
  'hashtags': nan},
 {'id': 2346367430,
  'link': 'https://twitter.com/realDonaldTrump/status/2346367430',
  'content': 'RE: Michael Jackson: "He was a great friend and a spectacular entertainer. It’s a devastating loss!" -Donald J. Trump',
  'date': '2009-06-26 11:51:16',
  'retweets': 106,
  'favorites': 266,
  'mentions': nan,
  'hashtags': nan},
 {'id': 2403435685,
  'link': 'https://twitter.com/realDonaldTrump/status/2403435685',
  'content': "Watch a powerful and frank interview with Donald Trump about the economy on Greta Van Susteren's On The Record: http://tinyurl.com/mmjked",
  'date': '2009-06-30 08:32:59',
  'retweets': 4,
  'favorites': 7,
  'mentions': nan,
  'hashtags': nan},
 {'id': 2475429091,
  'link': 'https://twitter.com/realDonaldTrump/status/2475429091',
  'content': "Here's to a safe and happy Independence Day for one and all - Enjoy it! --Donald J. Trump",
  'date': '2009-07-04 18:19:56',
  'retweets': 22,
  'favorites': 27,
  'mentions': nan,
  'hashtags': nan},
 {'id': 2614325575,
  'link': 'https://twitter.com/realDonaldTrump/status/2614325575',
  'content': '"Be aware of things that seem inexplicable because they can be a big step towards innovation." --Donald J. Trump http://tinyurl.com/pqpfvm',
  'date': '2009-07-13 09:03:38',
  'retweets': 14,
  'favorites': 28,
  'mentions': nan,
  'hashtags': nan},
 {'id': 2650952843,
  'link': 'https://twitter.com/realDonaldTrump/status/2650952843',
  'content': "Donald Trump backs 'Apprentice' Randal Pinkett for N.J. Lieutenant Governor: http://tinyurl.com/mvovzb",
  'date': '2009-07-15 08:40:35',
  'retweets': 6,
  'favorites': 6,
  'mentions': nan,
  'hashtags': nan},
 {'id': 2779566791,
  'link': 'https://twitter.com/realDonaldTrump/status/2779566791',
  'content': 'Congrats to winners from around the world who entered the "Think Like A Champion" signed book/keychain contest! http://tinyurl.com/pqpfvm',
  'date': '2009-07-22 10:32:52',
  'retweets': 9,
  'favorites': 10,
  'mentions': nan,
  'hashtags': nan},
 {'id': 2891870497,
  'link': 'https://twitter.com/realDonaldTrump/status/2891870497',
  'content': "Check out a list of Donald Trump's books for summer reading at the Trump University Blog: http://tinyurl.com/knyswt",
  'date': '2009-07-28 10:50:31',
  'retweets': 30,
  'favorites': 27,
  'mentions': nan,
  'hashtags': nan},
 {'id': 3124382438,
  'link': 'https://twitter.com/realDonaldTrump/status/3124382438',
  'content': "Browse Donald Trump's Summer Reading List for Business Success at the Trump University Blog: http://tinyurl.com/n5468r",
  'date': '2009-08-04 08:50:58',
  'retweets': 34,
  'favorites': 18,
  'mentions': nan,
  'hashtags': nan},
 {'id': 3246382217,
  'link': 'https://twitter.com/realDonaldTrump/status/3246382217',
  'content': '"Think. That’s the first step. Use all your power to utilize and develop that capability" --Donald J. Trump http://tinyurl.com/pqpfvm',
  'date': '2009-08-11 09:50:47',
  'retweets': 27,
  'favorites': 25,
  'mentions': nan,
  'hashtags': nan},
 {'id': 3308367056,
  'link': 'https://twitter.com/realDonaldTrump/status/3308367056',
  'content': 'Ivanka is now on Twitter - You can follow her @ IvankaTrump - Have a terrific weekend!',
  'date': '2009-08-14 09:33:46',
  'retweets': 38,
  'favorites': 55,
  'mentions': '@IvankaTrump',
  'hashtags': nan},
 {'id': 3427503309,
  'link': 'https://twitter.com/realDonaldTrump/status/3427503309',
  'content': "-- Watch Donald Trump's recent appearance on The Late Show with David Letterman: http://tinyurl.com/klts6b",
  'date': '2009-08-20 08:43:22',
  'retweets': 4,
  'favorites': 9,
  'mentions': nan,
  'hashtags': nan},
 {'id': 3450626731,
  'link': 'https://twitter.com/realDonaldTrump/status/3450626731',
  'content': 'Watch the Miss Universe competition LIVE from the Bahamas - Sunday, 8/23 @9pm (ET) on NBC: http://tinyurl.com/mrzad9',
  'date': '2009-08-21 09:32:45',
  'retweets': 14,
  'favorites': 5,
  'mentions': '@9pm',
  'hashtags': nan},
 {'id': 3498743628,
  'link': 'https://twitter.com/realDonaldTrump/status/3498743628',
  'content': 'Reminder: The Miss Universe competition will be LIVE from the Bahamas - Tonight @9pm (EST) on NBC: http://tinyurl.com/mrzad9',
  'date': '2009-08-23 16:12:37',
  'retweets': 10,
  'favorites': 12,
  'mentions': '@9pm',
  'hashtags': nan},
 {'id': 3627328938,
  'link': 'https://twitter.com/realDonaldTrump/status/3627328938',
  'content': '- Donald Trump bids to buy the Oreo Double Stuf Racing League. Check it out: http://www.nabiscoworld.com/oreo/dsrl/home.aspx',
  'date': '2009-08-29 11:23:56',
  'retweets': 255,
  'favorites': 363,
  'mentions': nan,
  'hashtags': nan},
 {'id': 3688564134,
  'link': 'https://twitter.com/realDonaldTrump/status/3688564134',
  'content': '- More hysterical DSRL videos featuring Donald Trump and "Double Trump" plus enter Golden Lick Race Sweepstakes: http://tinyurl.com/6asujj',
  'date': '2009-09-01 08:55:34',
  'retweets': 56,
  'favorites': 57,
  'mentions': nan,
  'hashtags': nan},
 {'id': 3982428551,
  'link': 'https://twitter.com/realDonaldTrump/status/3982428551',
  'content': "Read Donald Trump's Top Ten Tips for Success: http://tinyurl.com/mcn8yl",
  'date': '2009-09-14 10:50:14',
  'retweets': 29,
  'favorites': 35,
  'mentions': nan,
  'hashtags': nan},
 {'id': 4472353826,
  'link': 'https://twitter.com/realDonaldTrump/status/4472353826',
  'content': '"A lot of people have imagination, but can\'t execute--you have to execute with the imagination." --Donald J. Trump http://tinyurl.com/pqpfvm',
  'date': '2009-09-29 10:28:23',
  'retweets': 56,
  'favorites': 81,
  'mentions': nan,
  'hashtags': nan},
 {'id': 4629116949,
  'link': 'https://twitter.com/realDonaldTrump/status/4629116949',
  'content': "- Read what Donald Trump has to say about daughter Ivanka's upcoming new book, The Trump Card: http://tinyurl.com/ycsqmda",
  'date': '2009-10-05 09:37:38',
  'retweets': 8,
  'favorites': 7,
  'mentions': nan,
  'hashtags': nan},
 {'id': 4862580190,
  'link': 'https://twitter.com/realDonaldTrump/status/4862580190',
  'content': 'Watch video of Ivanka Trump sharing business advice with 4 entrepreneurial women on GMA: http://tinyurl.com/yk6hlfo',
  'date': '2009-10-14 09:13:17',
  'retweets': 11,
  'favorites': 10,
  'mentions': nan,
  'hashtags': nan},
 {'id': 5069623974,
  'link': 'https://twitter.com/realDonaldTrump/status/5069623974',
  'content': 'Hear Donald Trump discuss big gov spending, banks, & taxes on Your World w/Neil Cavuto: http://tinyurl.com/yhnzd7p',
  'date': '2009-10-22 08:57:04',
  'retweets': 6,
  'favorites': 5,
  'mentions': nan,
  'hashtags': nan},
 {'id': 5203117820,
  'link': 'https://twitter.com/realDonaldTrump/status/5203117820',
  'content': '--From Donald Trump: "Ivanka and Jared’s wedding was spectacular, and they make a beautiful couple. I’m a very proud father."',
  'date': '2009-10-27 10:31:48',
  'retweets': 8,
  'favorites': 12,
  'mentions': nan,
  'hashtags': nan},
 {'id': 5364614040,
  'link': 'https://twitter.com/realDonaldTrump/status/5364614040',
  'content': '--Work has begun, ahead of schedule, to build the greatest golf course in history: Trump International – Scotland.',
  'date': '2009-11-02 08:57:56',
  'retweets': 12,
  'favorites': 12,
  'mentions': nan,
  'hashtags': nan},
 {'id': 5775731054,
  'link': 'https://twitter.com/realDonaldTrump/status/5775731054',
  'content': "Donald Trump Partners with TV1 on New Reality Series Entitled, Omarosa's Ultimate Merger: http://tinyurl.com/yk5m3lc",
  'date': '2009-11-16 15:06:10',
  'retweets': 16,
  'favorites': 5,
  'mentions': nan,
  'hashtags': nan},
 {'id': 6090839867,
  'link': 'https://twitter.com/realDonaldTrump/status/6090839867',
  'content': 'Wishing you and yours a very Happy and Bountiful Thanksgiving!',
  'date': '2009-11-26 13:55:38',
  'retweets': 215,
  'favorites': 564,
  'mentions': nan,
  'hashtags': nan},
 {'id': 6312794445,
  'link': 'https://twitter.com/realDonaldTrump/status/6312794445',
  'content': 'Trump International Tower in Chicago ranked 6th tallest building in world by Council on Tall Buildings & Urban Habitat http://bit.ly/sqvQq',
  'date': '2009-12-03 13:39:09',
  'retweets': 40,
  'favorites': 47,
  'mentions': nan,
  'hashtags': nan},
 {'id': 6971079756,
  'link': 'https://twitter.com/realDonaldTrump/status/6971079756',
  'content': 'From Donald Trump: Wishing everyone a wonderful holiday & a happy, healthy, prosperous New Year. Let’s think like champions in 2010!',
  'date': '2009-12-23 11:38:18',
  'retweets': 221,
  'favorites': 234,
  'mentions': nan,
  'hashtags': nan},
 {'id': 7677152231,
  'link': 'https://twitter.com/realDonaldTrump/status/7677152231',
  'content': 'Celebrity Apprentice returns to NBC, Sunday, 3/14, 9-11PM ET/PT. Outstanding list of celebrities & season should be the best one yet!',
  'date': '2010-01-12 12:05:08',
  'retweets': 28,
  'favorites': 9,
  'mentions': nan,
  'hashtags': nan},
 {'id': 7793032738,
  'link': 'https://twitter.com/realDonaldTrump/status/7793032738',
  'content': "Trump Tycoon App for iPhone & iPod Touch - It's $2.99 but the advice is priceless! http://bit.ly/UGUF0",
  'date': '2010-01-15 10:28:02',
  'retweets': 270,
  'favorites': 325,
  'mentions': nan,
  'hashtags': nan},
 {'id': 8033746720,
  'link': 'https://twitter.com/realDonaldTrump/status/8033746720',
  'content': 'from Donald Trump: "I saw Lady Gaga last night and she was fantastic!"',
  'date': '2010-01-21 10:58:43',
  'retweets': 8772,
  'favorites': 8145,
  'mentions': nan,
  'hashtags': nan},
 {'id': 8083871612,
  'link': 'https://twitter.com/realDonaldTrump/status/8083871612',
  'content': "Golf Channel & Donald Trump's World of Golf host a Celebrity Match 1/25 @TNGC LA, CA - Mark Wahlberg vs. Kevin Dillon http://bit.ly/4MubN6",
  'date': '2010-01-22 14:51:00',
  'retweets': 19,
  'favorites': 5,
  'mentions': '@TNGC',
  'hashtags': nan},
 {'id': 8770493686,
  'link': 'https://twitter.com/realDonaldTrump/status/8770493686',
  'content': 'Superbowl Sunday is a great American tradition. The Colts and Saints are already champions, but may the best team win!',
  'date': '2010-02-07 10:54:42',
  'retweets': 31,
  'favorites': 20,
  'mentions': nan,
  'hashtags': nan},
 {'id': 8905123688,
  'link': 'https://twitter.com/realDonaldTrump/status/8905123688',

In [18]:
#each tweet is dictionary in list, heres tweet 1
print(json_list[0].keys())
print(json_list[0].values())
print(len(json_list[0].keys())) # of key value pairs

dict_keys(['id', 'link', 'content', 'date', 'retweets', 'favorites', 'mentions', 'hashtags'])
dict_values([1698308935, 'https://twitter.com/realDonaldTrump/status/1698308935', 'Be sure to tune in and watch Donald Trump on Late Night with David Letterman as he presents the Top Ten List tonight!', '2009-05-04 13:54:25', 510, 917, nan, nan])
8

In [ ]:
#show one key value pair of a given key #id : 1698308935
tweet_1 = json_list[0]
print(tweet_1)
print(f"id : {tweet_1['id']}")

{'id': 1698308935, 'link': 'https://twitter.com/realDonaldTrump/status/1698308935', 'content': 'Be sure to tune in and watch Donald Trump on Late Night with David Letterman as he presents the Top Ten List tonight!', 'date': '2009-05-04 13:54:25', 'retweets': 510, 'favorites': 917, 'mentions': nan, 'hashtags': nan}
id : 1698308935

In [ ]:
#show one key value pair #id : 1698308935
tweet_1_keys = list(tweet_1.keys())
tweet_1_values = list(tweet_1.values())
print(tweet_1_keys[0], ":", tweet_1_values[0])

id : 1698308935

In [21]:
#traverse the dictionary
for key in tweet_1.keys():
    print(key, tweet_1[key])

id 1698308935
link https://twitter.com/realDonaldTrump/status/1698308935
content Be sure to tune in and watch Donald Trump on Late Night with David Letterman as he presents the Top Ten List tonight!
date 2009-05-04 13:54:25
retweets 510
favorites 917
mentions nan
hashtags nan

In [ ]:
#what day was the the first tweet? #Monday
print(df['date'][0]) 
print(type(df['date'][0]))
print(df['date'][0].day_name()) #method, not a property

#what day was the the last tweet? #Wednesday
print("\n",len(df)-1)
print(df['date'][len(df)-1]) 
print(type(df['date'][len(df)-1]))
print(df['date'][len(df)-1].day_name()) #method, not a property

2009-05-04 13:54:25
<class 'pandas.Timestamp'>
Monday

 43351
2020-06-17 21:28:52
<class 'pandas.Timestamp'>
Wednesday

In [ ]:
#Which tweet was the longest? show id #278868249419063296
print(df.loc[df['content'].idxmax(),'id'])

#which day of the week had the most tweets? #Tuesday 7399
    #sum / group by day

#df['date'] = pd.to_datetime(df['date']) #convert to datetime object 
df.groupby(df['date'].dt.day_name())['content'].count()

278868249419063296

date
Friday       6371
Monday       7062
Saturday     4303
Sunday       4497
Thursday     6689
Tuesday      7399
Wednesday    7031
Name: content, dtype: int64

In [ ]:
df

,id,link,content,date,retweets,favorites,mentions,hashtags
0,1698308935,https://twitter.com/realDonaldTrump/status/169...,Be sure to tune in and watch Donald Trump on L...,2009-05-04 13:54:25,510,917,NaN,NaN
1,1701461182,https://twitter.com/realDonaldTrump/status/170...,Donald Trump will be appearing on The View tom...,2009-05-04 20:00:10,34,267,NaN,NaN
2,1737479987,https://twitter.com/realDonaldTrump/status/173...,Donald Trump reads Top Ten Financial Tips on L...,2009-05-08 08:38:08,13,19,NaN,NaN
3,1741160716,https://twitter.com/realDonaldTrump/status/174...,New Blog Post: Celebrity Apprentice Finale and...,2009-05-08 15:40:15,11,26,NaN,NaN
4,1773561338,https://twitter.com/realDonaldTrump/status/177...,"""My persona will never be that of a wallflower...",2009-05-12 09:07:28,1375,1945,NaN,NaN
...,...,...,...,...,...,...,...,...
43347,1273405198698975232,https://twitter.com/realDonaldTrump/status/127...,Joe Biden was a TOTAL FAILURE in Government. H...,2020-06-17 19:00:32,23402,116377,NaN,NaN
43348,1273408026968457216,https://twitter.com/realDonaldTrump/status/127...,Will be interviewed on @ seanhannity tonight a...,2020-06-17 19:11:47,11810,56659,@seanhannity,NaN
43349,1273442195161387008,https://twitter.com/realDonaldTrump/status/127...,pic.twitter.com/3lm1spbU8X,2020-06-17 21:27:33,4959,19344,NaN,NaN
43350,1273442469066276864,https://twitter.com/realDonaldTrump/status/127...,pic.twitter.com/vpCE5MadUz,2020-06-17 21:28:38,4627,17022,NaN,NaN
43351,1273442528411385858,https://twitter.com/realDonaldTrump/status/127...,pic.twitter.com/VLlc0BHW41,2020-06-17 21:28:52,3951,14344,NaN,NaN