In [1]:
import pandas as pd
data = pd.read_csv("amazon_10_years.csv", parse_dates=True, index_col=0)
data

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2011-01-03,9.068500,9.300000,9.060500,9.211000,9.211000,106628000
2011-01-04,9.307500,9.385000,9.189000,9.250500,9.250500,100636000
2011-01-05,9.205000,9.372500,9.203500,9.371000,9.371000,68376000
2011-01-06,9.325000,9.370500,9.262500,9.293000,9.293000,63594000
2011-01-07,9.394000,9.422500,9.187000,9.274500,9.274500,104434000
...,...,...,...,...,...,...
2020-12-23,160.250000,160.506500,159.208496,159.263504,159.263504,41876000
2020-12-24,159.695007,160.100006,158.449997,158.634506,158.634506,29038000
2020-12-28,159.699997,165.199997,158.634506,164.197998,164.197998,113736000
2020-12-29,165.496994,167.532501,164.061005,166.100006,166.100006,97458000
2020-12-30,167.050003,167.104996,164.123505,164.292496,164.292496,64186000

In [2]:
df = pd.DataFrame(data)
df

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2011-01-03,9.068500,9.300000,9.060500,9.211000,9.211000,106628000
2011-01-04,9.307500,9.385000,9.189000,9.250500,9.250500,100636000
2011-01-05,9.205000,9.372500,9.203500,9.371000,9.371000,68376000
2011-01-06,9.325000,9.370500,9.262500,9.293000,9.293000,63594000
2011-01-07,9.394000,9.422500,9.187000,9.274500,9.274500,104434000
...,...,...,...,...,...,...
2020-12-23,160.250000,160.506500,159.208496,159.263504,159.263504,41876000
2020-12-24,159.695007,160.100006,158.449997,158.634506,158.634506,29038000
2020-12-28,159.699997,165.199997,158.634506,164.197998,164.197998,113736000
2020-12-29,165.496994,167.532501,164.061005,166.100006,166.100006,97458000
2020-12-30,167.050003,167.104996,164.123505,164.292496,164.292496,64186000

In [3]:
#which date hhas the largest volume number
df.groupby(['Volume','Date']).max()

                           Open       High        Low      Close  Adj Close
Volume    Date
17626000  2019-12-24  89.690498  89.778503  89.378998  89.460503  89.460503
19688000  2012-12-24  12.865000  12.975000  12.848000  12.931000  12.931000
21824000  2015-12-24  33.167500  33.234001  33.029999  33.139500  33.139500
26634000  2012-07-03  11.457000  11.476500  11.379500  11.476500  11.476500
26868000  2015-07-02  21.850000  21.910000  21.674000  21.885500  21.885500
...                         ...        ...        ...        ...        ...
438188000 2015-07-24  28.949499  29.028500  26.467501  26.471001  26.471001
442338000 2012-04-27  11.241500  11.434500  11.011000  11.342500  11.342500
472460000 2011-04-27   9.160000   9.890000   9.137500   9.831500   9.831500
477122000 2015-01-30  17.316000  17.975000  17.037001  17.726500  17.726500
482684000 2011-10-26  10.184500  10.379000   9.825500   9.920000   9.920000

[2516 rows x 5 columns]

In [4]:
#which date has the lowest open value number 
df.groupby(['Open','Date']).max()

,,High,Low,Close,Adj Close,Volume
Open,Date,,,,,
8.059500,2011-03-18,8.177000,8.029500,8.091000,8.091000,148854000
8.069500,2011-03-15,8.344000,8.038000,8.254000,8.254000,98690000
8.115000,2011-03-23,8.313000,8.041000,8.266000,8.266000,94426000
8.168500,2011-03-21,8.289500,8.086000,8.226000,8.226000,81102000
8.203500,2011-03-22,8.222000,8.112500,8.130000,8.130000,72228000
...,...,...,...,...,...,...
172.502502,2020-08-27,172.649994,168.899994,170.000000,170.000000,85296000
173.399506,2020-10-13,174.619003,171.210999,172.181503,172.181503,114894000
174.250000,2020-09-03,174.420502,165.149994,168.399994,168.399994,163222000
174.479004,2020-09-01,175.693497,173.350006,174.955994,174.955994,68644000
177.350006,2020-09-02,177.612503,174.334503,176.572495,176.572495,78630000

In [8]:
#Which date has the largest positive difference between open and close prices? 
#(close price is higher than open price)
df.loc[(df['Close']-df['Open']).idxmax(),'Date']

KeyError: 'Date'

In [ ]:
#Which date has the largest negative difference between open and close prices? 
#(close price is lower than open price) 
#or 
#df.loc[(df['Close']-df['Open']).idxmin(),'Date']
df.loc[(df['Open']-df['Close']).idxmax(),'Date']

In [ ]:
#5.Question 5 Which year has the largest total volume number?
max_volume = df.loc[df['Volume'].idxmax(),'Date']
max_volume

In [ ]:
type(max_volume)

In [ ]:
from datetime import datetime
splitted = max_volume.split("-")
splitted

In [ ]:
date = datetime(int(splitted[0]),int(splitted[1]),int(splitted[2]))
date

In [ ]:
date.year

In [ ]:
#6. Question 6 Which weekday has the highest average volume number?
#Monday is 0
weekday_averages = df.groupby(df.index.weekday)['Volume'].mean()
weekday_averages

In [ ]:
# 7. Question 7 Create a time series line chart using Date and Close columns.
df_close = df[['Close']]
df_close.head(5)

In [ ]:
df_close.plot.line(y='Close')

In [ ]:
#8.0 Create a time series line chart using Date and Close columns, 
# Also add another line using rolling mean with window size 250. 
df['Moving Average'] = df['Close'].rolling(window=250).mean()
df_close.plot.line(y=['Close','Moving Average'])

In [ ]:
#9.0 Create a time series line chart using Date and Close column.
#Also add another line using rolling std with window size 250. 
df['Rolling Std'] = df['Close'].rolling(window=250).std()
df['Rolling Std']

In [ ]:
df_close.plot.line(y=['Close','Rolling Std'])