In [1]:
%pip install pandas
import pandas as pd
df_pop = pd.read_csv("us_pop.csv")
df_pop.head(5)

Requirement already satisfied: pandas in ./.venv/lib/python3.12/site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in ./.venv/lib/python3.12/site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

Note: you may need to restart the kernel to use updated packages.

  state     value
0    AL   4859000
1    AK    738400
2    AZ   6828000
3    AR   2978000
4    CA  39145000

In [2]:
%pip install plotly
import plotly.express as px
fig = px.choropleth(df_pop,
                    locations='state',
                    color='value',
                    color_continuous_scale='Viridis',
                    hover_name='state',
                    locationmode='USA-states',
                    labels={'value':'Population'})
fig.update_layout(
    title_text='State Populations',
    geo_scope='usa')

fig

Requirement already satisfied: plotly in ./.venv/lib/python3.12/site-packages (6.8.0)
Requirement already satisfied: narwhals>=1.15.1 in ./.venv/lib/python3.12/site-packages (from plotly) (2.22.1)
Requirement already satisfied: packaging in ./.venv/lib/python3.12/site-packages (from plotly) (26.2)
Note: you may need to restart the kernel to use updated packages.

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'coloraxis': 'coloraxis',
              'geo': 'geo',
              'hovertemplate': '<b>%{hovertext}</b><br><br>state=%{location}<br>Population=%{z}<extra></extra>',
              'hovertext': array(['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID',
                                  'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS',
                                  'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK',
                                  'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV',
                                  'WI', 'WY'], dtype=object),
              'locationmode': 'USA-states',
              'locations': array(['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID',
                                  'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS',
                                  'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK',
                                  'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV',
                                  'WI', 'WY'], dtype=object),
              'name': '',
              'type': 'choropleth',
              'z': {'bdata': ('eCRKAGBECwDgL2gA0HAtAChOVQJ0Ql' ... 'kAGOp/ANBnbQAgIxwA+A5YABzvCAA='),
                    'dtype': 'i4'}}],
    'layout': {'coloraxis': {'autocolorscale': False,
                             'colorbar': {'title': {'text': 'Population'}},
                             'colorscale': [[0.0, '#440154'], [0.1111111111111111,
                                            '#482878'], [0.2222222222222222,
                                            '#3e4989'], [0.3333333333333333,
                                            '#31688e'], [0.4444444444444444,
                                            '#26828e'], [0.5555555555555556,
                                            '#1f9e89'], [0.6666666666666666,
                                            '#35b779'], [0.7777777777777778,
                                            '#6ece58'], [0.8888888888888888,
                                            '#b5de2b'], [1.0, '#fde725']]},
               'geo': {'center': {}, 'domain': {'x': [0.0, 1.0], 'y': [0.0, 1.0]}, 'scope': 'usa'},
               'legend': {'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'title': {'text': 'State Populations'}}
})

In [ ]:
df_area = pd.read_csv('us_area.csv')
df_area.head(5)

  state     value
0    AL   52420.0
1    AK  665384.0
2    AZ  113990.0
3    AR   53179.0
4    CA  163695.0

In [ ]:
fig_2 = px.choropleth(df_area,
                      locations='state',
                      color='value',
                      hover_name='state',
                      locationmode='USA-states',
                      labels={'value':'Area'})
fig_2.update_layout(
    title_text='state areas',
    geo_scope='usa')

In [ ]:
#messy data example
df_covid = pd.read_csv("covid_19_world.csv")
df_covid.head(5)

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,popData2019,continentExp
0,12/14/2020,14,12,2020,746,6,Afghanistan,38041757.0,Asia
1,12/13/2020,13,12,2020,298,9,Afghanistan,38041757.0,Asia
2,12/12/2020,12,12,2020,113,11,Afghanistan,38041757.0,Asia
3,12/11/2020,11,12,2020,63,10,Afghanistan,38041757.0,Asia
4,12/10/2020,10,12,2020,202,16,Afghanistan,38041757.0,Asia

In [ ]:
df_covid.groupby('countriesAndTerritories')['cases'].count()

countriesAndTerritories
Afghanistan          340
Albania              281
Algeria              345
Andorra              276
Angola               268
                    ...
Wallis_and_Futuna     59
Western_Sahara       233
Yemen                249
Zambia               271
Zimbabwe             269
Name: cases, Length: 214, dtype: int64

In [ ]:
s = df_covid.groupby('countriesAndTerritories')['cases'].sum()
s

countriesAndTerritories
Afghanistan          49273
Albania              48530
Algeria              92102
Andorra               7338
Angola               16188
                     ...
Wallis_and_Futuna        3
Western_Sahara         766
Yemen                 2083
Zambia               18274
Zimbabwe             11246
Name: cases, Length: 214, dtype: int64

In [ ]:
#create new dataframe of index vs case sum
df_cases = pd.DataFrame({'Country':s.index, 'Cases':s.values})
df_cases

               Country  Cases
0          Afghanistan  49273
1              Albania  48530
2              Algeria  92102
3              Andorra   7338
4               Angola  16188
..                 ...    ...
209  Wallis_and_Futuna      3
210     Western_Sahara    766
211              Yemen   2083
212             Zambia  18274
213           Zimbabwe  11246

[214 rows x 2 columns]

In [ ]:
#map country by ISO 3 letter standard
iso_names = pd.read_csv("country_iso.csv", encoding = 'latin-1')
iso_names

             Country iso_2 iso_3  iso_4
0       Afghanistan    AF   AFG       4
1           Albania    AL   ALB       8
2           Algeria    DZ   DZA      12
3    American Samoa    AS   ASM      16
4           Andorra    AD   AND      20
..               ...   ...   ...    ...
244  Western Sahara    EH   ESH     732
245           Yemen    YE   YEM     887
246          Zambia    ZM   ZMB     894
247        Zimbabwe    ZW   ZWE     716
248   Åland Islands    AX   ALA     248

[249 rows x 4 columns]

In [ ]:
iso_names['iso_3']

0      AFG
1      ALB
2      DZA
3      ASM
4      AND
       ...
244    ESH
245    YEM
246    ZMB
247    ZWE
248    ALA
Name: iso_3, Length: 249, dtype: object

In [ ]:
#pull the country names column out of DF as a list and remove white space
country_names = list(iso_names['Country'])
country_name_clean = []
for name in country_names:
    country_name_clean.append(name.strip())
country_iso = list(iso_names['iso_3'])

In [ ]:
country_iso_matched = []
country_names_matched = []
country_cases_matched = []
for i in range(len(df_cases)):
    #print(df_cases.iloc[i,0])
    name = df_cases.iloc[i,0]
    for j in range(len(country_name_clean)):
        if name == country_name_clean[j]:
           # print(name)
            #print(country_iso[j])
            country_names_matched.append(name)
            country_iso_matched.append(country_iso[j].strip())
            country_cases_matched.append(df_cases.iloc[i, 1])
            #print("-----------------------")

In [ ]:
dict_new = {'country':country_names_matched, 'iso':country_iso_matched, 'cases':country_cases_matched}
df_final = pd.DataFrame(dict_new)
df_final.head(5)

       country  iso  cases
0  Afghanistan  AFG  49273
1      Albania  ALB  48530
2      Algeria  DZA  92102
3      Andorra  AND   7338
4       Angola  AGO  16188

In [ ]:
# Plot and show the choropleth map.
%pip install plotly
%pip install plotly[express]
%pip install numpy 
import plotly.express as px
import plotly.io as pio
pio.renderers.default = "notebook"
fig = px.choropleth(df_final, locations="iso",
                    color="cases", # lifeExp is a column of gapminder
                    hover_name="country", # column to add to hover information
                    color_continuous_scale=px.colors.sequential.Plasma)
fig.show()

Requirement already satisfied: plotly in ./.venv/lib/python3.12/site-packages (6.8.0)
Requirement already satisfied: narwhals>=1.15.1 in ./.venv/lib/python3.12/site-packages (from plotly) (2.22.1)
Requirement already satisfied: packaging in ./.venv/lib/python3.12/site-packages (from plotly) (26.2)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: plotly[express] in ./.venv/lib/python3.12/site-packages (6.8.0)
Requirement already satisfied: narwhals>=1.15.1 in ./.venv/lib/python3.12/site-packages (from plotly[express]) (2.22.1)
Requirement already satisfied: packaging in ./.venv/lib/python3.12/site-packages (from plotly[express]) (26.2)
Requirement already satisfied: numpy>=1.22 in ./.venv/lib/python3.12/site-packages (from plotly[express]) (2.4.6)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: numpy in ./.venv/lib/python3.12/site-packages (2.4.6)
Note: you may need to restart the kernel to use updated packages.

ImportError: Plotly Express requires numpy to be installed. You can install numpy using pip with:

$ pip install numpy

Or install Plotly Express and its dependencies directly with:

$ pip install "plotly[express]"

You can also use Plotly Graph Objects to create a large number of charts without installing
numpy. See examples here: https://plotly.com/python/graph-objects/